# MODE="LIVE|BUILD" docker compose up --build
#
# Navigate to http://localhost/docs/
services:
  docs:
    # image: datajoint/datajoint-docs
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MODE
    volumes:
      - .:/main
    ports:
      - 8000:8000
    command:
      - sh
      - -c
      - |
        set -e
        if echo "$${MODE}" | grep -i live &>/dev/null; then
            mkdocs serve --config-file ./mkdocs.yaml -a 0.0.0.0:8000
        elif echo "$${MODE}" | grep -i build &>/dev/null; then
            mkdocs build --config-file ./mkdocs.yaml
        else
            echo "Unexpected mode..."
            exit 1
        fi
