# MODE="LIVE|BUILD" docker compose up --build
#
# Navigate to http://localhost/docs/
services:
  docs:
    build:
      args:
        - BOT_PAT
    image: datajoint/datajoint-docs
    environment:
      - MODE
    volumes:
      - .:/main
    ports:
      - 80:80
    command:
      - sh
      - -c
      - |
        set -e
        if echo "$${MODE}" | grep -i live &>/dev/null; then
            mkdocs serve --config-file ./mkdocs.yaml
        elif echo "$${MODE}" | grep -i build &>/dev/null; then
            mkdocs build --config-file ./mkdocs.yaml
        else
            echo "Unexpected mode..."
            exit 1
        fi
